const SET_CURRENT_PHOTO = "SET_CURRENT_PHOTO";
const ADD_PHOTO = "ADD_PHOTO";
const TOGGLE_CONFIG = "TOGGLE_CONFIG";
const SET_MODE = "SET_MODE";
const SET_THEME = "SET_THEME";
const ORDER_IMAGES = "ORDER_IMAGES";
const TOGGLE_UPLOAD_AREA = "TOGGLE_UPLOAD_AREA";

export {
  SET_CURRENT_PHOTO,
  ADD_PHOTO,
  TOGGLE_CONFIG,
  SET_MODE,
  SET_THEME,
  ORDER_IMAGES,
  TOGGLE_UPLOAD_AREA,
};
